### ISSUE TITLE
I am getting this an error when testing this generator

### ISSUE THREAD

**Issue by CarlosBalladares** [thREam/generator-keystone-vue#1]
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/carlosballadares/NodejsProjects/keystonevue/testvue/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/carlosballadares/NodejsProjects/keystonevue/testvue/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

Any guidance will be appreciated as i'm learning to use keystone

**Comment by NoahCardoza** [comment]
I am getting the same error...

**Comment by ragnaroaldset-zz** [comment]
Same
